### ISSUE TITLE
User data directory

### ISSUE THREAD

**Issue by hgamal** [flathub/network.bisq.Bisq#4]
After installation, Flatpak's Bisq does not allow the application to write to the directory ~/.local/share/Bisq. It causes all accounts, funds, configurations, etc., to be lost after the program is closed. For example, the next time the program run, all keys are created again. If bitcoins are transferred to the address of the first run, they are lost. I lost US$ 100.00 using it.

I don't know if any additional configuration should be done after the flatpack package installation. If there is any, it is very well hidden.

**Comment by fleshin** [comment]
Same here.Cannot perform backup/restore as home directory appears empty.

**Comment by hgamal** [comment]
I know that, but I think the package should be ready to work after being
installed. I doubt that any regular or entry-level user would be aware of
it. The way the package is defined, it is a BUG.

**Comment by razzeee** [comment]
https://github.com/bisq-network/bisq/search?q=%2F.local%2Fshare%2FBisq suggests that might be true

**Comment by nanonyme** [comment]
That is a clear bug in bisq that it doesn't follow XDG_DATA_HOME but it seems like fastest way to workaround this by adding --persist to the manifest.

**Comment by Erick555** [comment]
@hgamal you are absolutely right it's bug in package but we need confirmation if proposed fix works.

**Comment by TingPing** [comment]
Added persist 2091f9733bc7a42fc156ebed0e4767244ba07a1f.

**Comment by mfilipe** [comment]
This bug persists. I had to add filesystem access to `home` with read/write to allow Bisq uses `~/.local/share/Bisq`.

**Comment by TingPing** [comment]
@mfilipe What you are saying doesn't make sense, it already has permissions to write to a persistent `~/.local/share/Bisq`, `home` permissions just breaks it.

**Comment by mfilipe** [comment]
> @mfilipe What you are saying doesn't make sense, it already has permissions to write to a persistent `~/.local/share/Bisq`, `home` permissions just breaks it.

Really strange. Tested again and same behavior: if I remove `--filesystem=home`, Bisq runs without my setup like the first time I run it. 

I don't know if this matters, but I ran Bisq using RPM format before in Fedora (now using openSUSE Tumbleweed).

**Comment by TingPing** [comment]
> I don't know if this matters, but I ran Bisq using RPM format before in Fedora (now using openSUSE Tumbleweed).

Yes of course. The file path is `~/.var/app/network.bisq.Bisq/.local/share/Bisq` for Flatpak.

**Comment by mfilipe** [comment]
> Yes of course. The file path is `~/.var/app/network.bisq.Bisq/.local/share/Bisq` for Flatpak.

Thanks, @TingPing! Moving the backup to this path, it works. 

Now I understand `--persist`: it makes a persist volume inside the sandbox environment instead of my home.
